name: RetroFutureGameEngine-Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: HelloWorldScript
        run: echo Hello, world!

      - name: HelloAndByeScript
        run: |
          echo Hi!
          echo Bye!
